version: '3'
services:
  streamlit:
    container_name: streamlit_app
    build: .
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1

  db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: youtube_api_db      
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:    # Define a named volume to persist MySQL data
  

